trigger:
  - main  # Replace 'main' with your branch name (e.g., 'master') if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Create and write "Hello, World!" to hello.txt
      echo "Hello, World!" > hello.txt
    displayName: 'Create hello.txt'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'hello-artifact'
    displayName: 'Publish Artifact'

